### ISSUE TITLE
Lab3 Review s292634

### ISSUE THREAD

**Issue by jacopotaramax** [saccuz/Computational_Intelligence#6]
## General Overview 
The code looks well-ordered, I'd rather suggest to add a readme in the lab3 directory just to get the viewer conscious of what have been done before opening  the task1_2 directory. It's just an advice to better present the work to someone who does not know anything about it. 
In the task1_2 code there's some lackness of commenting, might be useful to add them to help code reviewing.

### Genetic Algorithm
The GA you implemented works well on my notebook but I have some minor things to annotate.
I found new individuals generation a little hard and not necessarily sophisticated.
The evolution function is instead interesting, good results also trying different EVOLV_STEP
I'm not sure to have correctly understood the RESULT_TRESH motivations, maybe you can add more comments to that, also in the readme there's anything about.

### Min Max
It's a good min-max algorithm: it works well and it's also confirmed by the graphs. I found interesting the usage of searching the winning path. 
Just an observation on the code: where you call evaluate function, you forgot we already have a boolean method in nim, evaluate become redundant.
Possible implementaions may be adding a prune, just to limit the number of computations if the nim values grows.

### Reinforced Learning
I found the code quite hard to understand beacuse of no many comments near the code, i suggest to add at least something about the reward process. 
The algorithm need to be made lighter because is quite computationally heavy, but works.

**Comment by saccuz** [comment]
I don't understand the annotation about the individuals generation. Could you be more precise?
The RESULT_TRESH is just an arbitrary treshold to perform the points distribution inside the genome.
The evaluation function exploit te boolean method of Nim. Nontheless I agree, as the function could have been written better to exploit more the property.
The prune is present, as we check either the depth we reached and also if the value is already the one the minmax will utilize.
For RL we weren't able to optimize after a certain amount due to time constraint.
